env:
  global:
    - SWIFT_VERSION=5.1
    - CODECOV_TOKEN="783e1c34-5bb1-4ab2-a0e9-da55ce878384"
matrix:
  include:
    - os: linux
      language: generic
      dist: trusty
      sudo: required
      install:
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script:
        - swift package update
        - swift test

    - os: osx
      osx_image: xcode10.1
      language: swift
      sudo: required
      install:
        - sudo gem install jazzy
      script:
        - swift package update
        - swift test
      after_success:
        - bash <(curl -s https://codecov.io/bash)
