env:
  global:
    - SWIFT_BRANCH=development
    - SWIFT_VERSION=swift-DEVELOPMENT-SNAPSHOT-2019-01-19-a
matrix:
  include:
    - os: linux
      language: generic
      dist: trusty
      sudo: required
      install:
        - sudo apt-get install clang libicu-dev
        - mkdir swift
        - curl https://swift.org/builds/$SWIFT_BRANCH/ubuntu1604/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu16.04.tar.gz -s | tar xz -C swift &> /dev/null
        - export PATH="$(pwd)/swift/$SWIFT_VERSION-ubuntu16.04/usr/bin:$PATH"
      script:
        - swift package update
        - swift test

    - os: osx
      osx_image: xcode10.1
      language: swift
      script:
        - swift package update
        - swift test

        #https://swift.org/builds/development/ubuntu1604/swift-DEVELOPMENT-SNAPSHOT-2019-01-19-a/swift-DEVELOPMENT-SNAPSHOT-2019-01-19-a-ubuntu16.04.tar.gz